# Generated by Django 3.0.3 on 2020-04-09 00:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import helpers.s3
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(max_length=32, verbose_name='identificador')),
            ],
            options={
                'verbose_name': 'meio de entrega',
                'verbose_name_plural': 'meios de entrega',
            },
        ),
        migrations.CreateModel(
            name='OrderMean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(max_length=32, verbose_name='identificador')),
            ],
            options={
                'verbose_name': 'meio de pedir',
                'verbose_name_plural': 'meios de pedir',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=64, verbose_name='nome')),
                ('description', models.TextField(max_length=1024, verbose_name='descrição')),
                ('neighborhood', models.CharField(max_length=64, verbose_name='bairro')),
                ('city', models.CharField(max_length=64, verbose_name='cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='estado')),
                ('telephone_number', models.CharField(max_length=24, validators=[django.core.validators.RegexValidator('^[0-9()+-].+$')], verbose_name='número de telefone')),
                ('whatsapp_number', models.CharField(blank=True, max_length=24, null=True, validators=[django.core.validators.RegexValidator('^[0-9()+-].+$')], verbose_name='número do Whatsapp')),
                ('instagram_profile', models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator('^@(?!.*\\.\\.)(?!.*\\.$)[^\\W][\\w.]{0,29}$')], verbose_name='perfil do Instagram')),
                ('ifood_url', models.URLField(blank=True, null=True, verbose_name='link do iFood')),
                ('uber_eats_url', models.URLField(blank=True, null=True, verbose_name='link do Uber Eats')),
                ('rappi_url', models.URLField(blank=True, null=True, verbose_name='link do Rappi')),
                ('site_url', models.URLField(blank=True, null=True, verbose_name='link do site')),
                ('cover_image', models.ImageField(upload_to=helpers.s3.UploadFileTo('sellers', 'cover'), verbose_name='foto de capa')),
                ('referrals', models.CharField(blank=True, choices=[('friends', 'Friends'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('others', 'others')], max_length=16, null=True, verbose_name='como você nos achou')),
                ('is_approved', models.BooleanField(default=False, verbose_name='aprovado')),
                ('delivery_means', models.ManyToManyField(related_name='sellers', to='seller.DeliveryMean', verbose_name='meios de entrega')),
                ('order_means', models.ManyToManyField(related_name='sellers', to='seller.OrderMean', verbose_name='meios de pedido')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'vendedor',
                'verbose_name_plural': 'vendedores',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('image', models.ImageField(upload_to=helpers.s3.UploadFileTo('products', 'image'), verbose_name='foto')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='seller.Seller', verbose_name='vendedor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
