# Generated by Django 3.0.3 on 2020-04-09 04:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_means'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='ordem'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='instagram_profile',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^@(?!.*\\.\\.)(?!.*\\.$)[^\\W][\\w.]{0,29}$')], verbose_name='perfil do Instagram'),
        ),
    ]
