# Generated by Django 3.0.3 on 2020-04-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20200410_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='referrals',
            field=models.CharField(blank=True, choices=[('friends', 'Amigos'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('others', 'Outros')], max_length=16, null=True, verbose_name='como você nos achou'),
        ),
    ]
