# Generated by Django 3.0.3 on 2020-04-22 01:21

from django.db import migrations, models
import helpers.s3


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20200410_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='legacy_image',
            field=models.URLField(blank=True, help_text='Link do Drive, para o processo de inscrição antigo', null=True, verbose_name='imagem legado'),
        ),
        migrations.AddField(
            model_name='seller',
            name='legacy_cover_image',
            field=models.URLField(blank=True, null=True, verbose_name='foto de capa legado'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(null=True, upload_to=helpers.s3.UploadFileTo('products', 'image'), verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=helpers.s3.UploadFileTo('sellers', 'cover'), verbose_name='foto de capa'),
        ),
    ]
