# Generated by Django 3.0.3 on 2020-04-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20200421_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='ifood_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='link do iFood'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='rappi_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='link do Rappi'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='site_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='link do site'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='uber_eats_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='link do Uber Eats'),
        ),
    ]
